const TEST_GROUPS = Object.freeze({
    "quick:workflow": {
        execution: "parallel",
        tests: [
            "tools/architecture_dependencies.test.cjs",
            "tools/docs_check.test.cjs",
            "tools/final_operation_compatibility_docs.test.cjs",
            "tools/log_readability.test.cjs",
            "tools/sampled_log.test.cjs",
            "tools/test-workflow/benchmark.test.cjs",
            "tools/test-workflow/build-cn.test.cjs",
            "tools/test-workflow/package-scripts.test.cjs",
            "tools/test-workflow/select-tests.test.cjs",
            "tools/test-workflow/run.test.cjs",
            "tools/test-workflow/verify-cn-build.test.cjs",
            "tools/c5_common_projection_route.test.cjs",
            "tools/common_response_entities.test.cjs",
            "tools/common_response_projector.test.cjs",
            "tools/debt_t07_field_characterization.test.cjs",
            "tools/perf/http_metrics.test.cjs",
            "tools/perf/http_baseline.test.cjs",
            "tools/perf/tcp_baseline.test.cjs",
        ],
    },
    "quick:runtime": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/server_bundle.test.cjs",
            "tools/server_bundle_zip.test.cjs",
            "tools/runtime_pack.test.cjs",
            "tools/runtime_bundle_metadata.test.cjs",
            "tools/runtime_config.test.cjs",
            "tools/ios_runtime_config.test.cjs",
            "tools/multi_hub_credentials.test.cjs",
            "tools/multi_hub_authentication.test.cjs",
            "tools/multi_hub_cli_env.test.cjs",
            "tools/multi_management_service.test.cjs",
            "tools/multi_management_routes.test.cjs",
            "tools/multi_hub_control.test.cjs",
            "tools/multi_hub_idempotency.test.cjs",
            "tools/multi_hub_session_cleanup.test.cjs",
            "tools/multi_hub_token.test.cjs",
            "tools/multi_runtime_config.test.cjs",
            "tools/multi_client_fallback.test.cjs",
            "tools/account_identity_provider.test.cjs",
            "tools/multi_runtime_session_options.test.cjs",
            "tools/api_index_time_semantics.test.cjs",
            "tools/time_semantics.test.cjs",
            "tools/game_calendar.test.cjs",
            "tools/game_calendar_source_guard.test.cjs",
            "tools/exp_pool_time.test.cjs",
            "tools/comic_route.test.cjs",
            "tools/admin_server_status_runtime_config.test.cjs",
            "tools/cn_tool_capabilities.test.cjs",
            "tools/runtime_admin.test.cjs",
            "tools/admin_multi_status.test.cjs",
            "tools/runtime_health.test.cjs",
            "tools/runtime_lifecycle.test.cjs",
            "tools/runtime_native_binding.test.cjs",
            "tools/server_time_service.test.cjs",
            "tools/server_time_routes.test.cjs",
            "tools/runtime_capabilities.test.cjs",
            "tools/runtime_capabilities_wiring.test.cjs",
            "tools/release_contract.test.cjs",
            "tools/udid_probe.test.cjs",
            "tools/ios_ipa_patch.test.cjs",
            "tools/build_client.test.cjs",
            "tools/rename_package.test.cjs",
        ],
    },
    "quick:modes": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/modes_loader.test.cjs",
            "tools/modes_contract.test.cjs",
            "tools/modes_integration.test.cjs",
            "tools/modes_routes.test.cjs",
            "tools/modes_lifecycle.test.cjs",
            "tools/modes_wiring.test.cjs",
        ],
    },
    "quick:seed": {
        execution: "parallel",
        tests: [
            "tools/gacha_faithful_inspect.test.cjs",
            "tools/gacha_seed_catalog_builder.test.cjs",
            "tools/gacha_seed_catalog_cli.test.cjs",
            "tools/gacha_seed_quarantine.test.cjs",
            "tools/seed_api.test.cjs",
        ],
    },
    "quick:gacha": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/gacha_catalog.test.cjs",
            "tools/gacha_crazy_conversion.test.cjs",
            "tools/gacha_draw_weights.test.cjs",
            "tools/gacha_equipment_movie.test.cjs",
            "tools/gacha_execution_owner.test.cjs",
            "tools/gacha_exec_plan.test.cjs",
            "tools/gacha_response_projection.test.cjs",
            "tools/gacha_rules.test.cjs",
            "tools/gacha_sampled_logging.test.cjs",
            "tools/gacha_seed_catalog_runtime.test.cjs",
        ],
    },
    "quick:quest": {
        execution: "parallel",
        tests: [
            "tools/active_quest_service_import.test.cjs",
            "tools/additional_reward_routes.test.cjs",
            "tools/reward_campaign_routes.test.cjs",
            "tools/quest_sampled_logging.test.cjs",
            "tools/quest_session_identity.test.cjs",
            "tools/quest_recent_other_player_party_route.test.cjs",
            "tools/single_continue_request.test.cjs",
            "tools/single_continue_idempotency.test.cjs",
            "tools/single_continue_lifecycle.test.cjs",
            "tools/special_quest_flow.test.cjs",
            "tools/periodic_reward_settlement.test.cjs",
            "tools/daily_challenge_and_shop_time.test.cjs",
        ],
    },
    "quick:character-growth": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/character_growth_core.test.cjs",
            "tools/character_growth_context.test.cjs",
            "tools/character_growth_response_projector.test.cjs",
            "tools/character_growth_load_projector.test.cjs",
            "tools/character_growth_client_merge.test.cjs",
            "tools/character_growth_bond_command.test.cjs",
            "tools/character_growth_bond_qualification.test.cjs",
            "tools/character_growth_metadata_commands.test.cjs",
            "tools/character_growth_open_board_command.test.cjs",
            "tools/character_growth_node_commands.test.cjs",
            "tools/character_growth_awake_node_commands.test.cjs",
            "tools/character_growth_node_transaction.test.cjs",
            "tools/character_growth_exp_commands.test.cjs",
            "tools/character_growth_stack_commands.test.cjs",
            "tools/character_growth_over_limit_commands.test.cjs",
            "tools/character_growth_exp_transaction.test.cjs",
            "tools/character_growth_lavu_orderings.test.cjs",
            "tools/character_growth_gate_acceptance.test.cjs",
            "tools/growth_response_projection.test.cjs",
            "tools/perf/character_growth_context_admission.test.cjs",
        ],
    },
    "quick:character": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/character_awake_eligibility.test.cjs",
            "tools/character_evolution.test.cjs",
            "tools/character_evolution_route.test.cjs",
            "tools/character_growth_transaction.test.cjs",
            "tools/character_growth_open_board_transaction.test.cjs",
            "tools/character_mana_mutation_content.test.cjs",
            "tools/character_mana_mutation_http.test.cjs",
            "tools/character_mana_mutation_plan.test.cjs",
            "tools/ex_boost_pending_draw.test.cjs",
            "tools/small_write_route_boundaries.test.cjs",
            "tools/mana_board_availability.test.cjs",
            "tools/player_awake_save_roundtrip.test.cjs",
        ],
    },
    "quick:protocol": {
        execution: "parallel",
        // Spawn-heavy group: global_embedded_startup boots src/server.ts under
        // ts-node (~15-25s per probe; ts-node 10 has no persistent transpile
        // cache) and the lifecycle suites spawn servers, so 60s per file
        // flakes under group load (same rationale as integration:party).
        timeoutMs: 120_000,
        tests: [
            "tools/handshake_lifecycle.test.cjs",
            "tools/global_embedded_startup.test.cjs",
            "tools/lobby_lifecycle.test.cjs",
            "tools/msgpack_compat.test.cjs",
            "tools/multi_admission.test.cjs",
            "tools/multi_battle_relay_snapshot.test.cjs",
            "tools/multi_battle_multiscene.test.cjs",
            "tools/multi_lobby_battle_lock.test.cjs",
            "tools/multi_battle_start_boundary.test.cjs",
            "tools/multi_release_boundary.test.cjs",
            "tools/multi_session_client_state.test.cjs",
            "tools/multi_runtime_snapshot.test.cjs",
            "tools/multi_battle_heartbeat.test.cjs",
            "tools/multi_compatibility.test.cjs",
            "tools/multi_coordinator_contract.test.cjs",
            "tools/multi_coordinator_embedded.test.cjs",
            "tools/multi_coordinator_router.test.cjs",
            "tools/multi_lifecycle_faults.test.cjs",
            "tools/multi_context_initialization.test.cjs",
            "tools/multi_finish_follow_info.test.cjs",
            "tools/multi_player_context.test.cjs",
            "tools/multi_player_snapshot.test.cjs",
            "tools/multi_quest_availability.test.cjs",
            "tools/multi_reliable_send.test.cjs",
            "tools/multi_remote_coordinator.test.cjs",
            "tools/multi_remote_settlement.test.cjs",
            "tools/multi_load_recovery.test.cjs",
            "tools/multi_room_handshake_identity.test.cjs",
            "tools/multi_room_identity.test.cjs",
            "tools/npc_contributor_names.test.cjs",
            "tools/npc_nickname_pool.test.cjs",
            "tools/room_cleanup_lifecycle.test.cjs",
            "tools/room_dismissal_lifecycle.test.cjs",
            "tools/session_frame_order.test.cjs",
            "tools/session_server_lifecycle.test.cjs",
            "tools/multi_tcp_guardrails.test.cjs",
            "tools/multi_raising_state_mapping.test.cjs",
            "tools/multi_follow_stamina.test.cjs",
            "tools/multi_mates_self_projection.test.cjs",
            "tools/gift_capability.test.cjs",
            "tools/gift_code_lifecycle.test.cjs",
            "tools/gift_receive_route.test.cjs",
            "tools/attention_config_route.test.cjs",
            "tools/active_account_state_cache.test.cjs",
            "tools/load_identity_boundary.test.cjs",
        ],
    },
    "quick:cdn": {
        execution: "parallel",
        tests: [
            "tools/cdn_catalog.test.cjs",
            "tools/cdn_archive_sources.test.cjs",
            "tools/cdn_patch_manifest.test.cjs",
            "tools/cdn_patch_overlay.test.cjs",
            "tools/cdn_patch_check.test.cjs",
            "tools/admin_content_status.test.cjs",
            "tools/cdn_paths.test.cjs",
            "tools/cdn_planner.test.cjs",
            "tools/cdn_types.test.cjs",
        ],
    },
    "quick:content": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/character_content.test.cjs",
            "tools/content_character_converter.test.cjs",
            "tools/content_character_mana_admission_converter.test.cjs",
            "tools/character_level_seed.test.cjs",
            "tools/content_character_election_converter.test.cjs",
            "tools/content_asset_audit.test.cjs",
            "tools/content_additional_reward_converter.test.cjs",
            "tools/content_skill_effects_converter.test.cjs",
            "tools/content_amf3.test.cjs",
            "tools/content_box_gacha_converter.test.cjs",
            "tools/box_gacha_content.test.cjs",
            "tools/ex_boost_content.test.cjs",
            "tools/character_election_content.test.cjs",
            "tools/exchange_content_boundary.test.cjs",
            "tools/content_gacha_converter.test.cjs",
            "tools/content_gameplay_converter.test.cjs",
            "tools/content_gameplay_runtime.test.cjs",
            "tools/config_content.test.cjs",
            "tools/content_item_equipment_converter.test.cjs",
            "tools/item_equipment_content.test.cjs",
            "tools/quest_daily_content.test.cjs",
            "tools/login_bonus_content.test.cjs",
            "tools/reward_content_catalog.test.cjs",
            "tools/encyclopedia_content.test.cjs",
            "tools/player_rank_content.test.cjs",
            "tools/inventory_c1_plans.test.cjs",
            "tools/item_overflow_disposition.test.cjs",
            "tools/item_overflow_common_response.test.cjs",
            "tools/inventory_c1_structure.test.cjs",
            "tools/content_login_bonus_converter.test.cjs",
            "tools/content_mana_node_converter.test.cjs",
            "tools/mana_board_parent_index.test.cjs",
            "tools/content_quest_converter.test.cjs",
            "tools/content_reward_campaign_converter.test.cjs",
            "tools/content_reward_converter.test.cjs",
            "tools/reward_campaign_runtime.test.cjs",
            "tools/content_reward_repository.test.cjs",
            "tools/content_runtime_index_contract.test.cjs",
            "tools/content_runtime_test_fixture_authority.test.cjs",
            "tools/content_runtime_index_boundary.test.cjs",
            "tools/content_runtime_authority.test.cjs",
            "tools/content_runtime_endpoint_tables.test.cjs",
            "tools/content_runtime_direct_tables.test.cjs",
            "tools/content_runtime_mission_tables.test.cjs",
            "tools/event_content_boundary.test.cjs",
            "tools/mission_catalog_startup_boundary.test.cjs",
            "tools/quest_practice_content_boundary.test.cjs",
            "tools/stamina_content_boundary.test.cjs",
            "tools/content_shop_converter.test.cjs",
            "tools/gacha_repository.test.cjs",
            "tools/shop_repository.test.cjs",
            "tools/shop_catalog.test.cjs",
            "tools/content_repository.test.cjs",
            "tools/content_snapshot_configuration.test.cjs",
            "tools/content_startup.test.cjs",
            "tools/content_sync_entry.test.cjs",
            "tools/content_sync.test.cjs",
            "tools/content_object_store.test.cjs",
            "tools/content_archive_index.test.cjs",
            "tools/content_ordered_map.test.cjs",
            "tools/content_registry.test.cjs",
            "tools/content_schema.test.cjs",
            "tools/quest_reward_configuration.test.cjs",
            "tools/quest_reward_route_boundary.test.cjs",
            "tools/first_clear_reward.test.cjs",
            "tools/news-visibility.test.cjs",
            "tools/news_html_shell_projection.test.cjs",
            "tools/news_routes.test.cjs",
            "tools/forced_news_route.test.cjs",
        ],
    },
    "integration:compiled": {
        execution: "parallel",
        tests: [
            "tools/quest_abort_route.test.cjs",
            "tools/score_attack_event.test.cjs",
            "tools/treasure_key_entry.test.cjs",
        ],
    },
    "integration:runtime": {
        execution: "serial",
        timeoutMs: 360_000,
        tests: [
            "tools/runtime_compiled_smoke.test.cjs",
        ],
    },
    "integration:multi-hub": {
        execution: "serial",
        timeoutMs: 120_000,
        tests: [
            "tests/multi-hub-battle-flow.test.js",
            "tests/multi-hub-process-harness.test.js",
            "tools/perf/multi_hub_load_metrics.test.cjs",
            "tools/perf/multi_hub_load_signature.test.cjs",
            "tools/perf/multi_hub_load_process_fixture.test.cjs",
            "tools/perf/multi_hub_load_workload_resilience.test.cjs",
            "tools/perf/full_server_acceptance_safety.test.cjs",
            "tools/perf/full_server_acceptance.test.cjs",
            "tests/multi-hub-process.test.js",
            "tools/perf/hub_baseline.test.cjs",
            "tools/perf/multi_hub_load_workload.test.cjs",
        ],
    },
    "integration:content": {
        execution: "serial",
        tests: [
            "tools/content_dynamic_catalog.test.cjs",
            "tools/content_dynamic_catalog_integration.test.cjs",
            "tools/shop_repository_integration.test.cjs",
            "tools/content_sync_smoke.test.cjs",
        ],
    },
    "integration:mission-compiled": {
        execution: "parallel",
        tests: [
            "tools/character_awake_refresh.test.cjs",
            "tools/mission_completion.test.cjs",
        ],
    },
    "integration:rules": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/additional_reward.test.cjs",
            "tools/character_mana_batch_writes.test.cjs",
            "tools/character_stack.test.cjs",
            "tools/database_hot_path_indexes.test.cjs",
            "tools/equipment_batch_reads.test.cjs",
            "tools/equipment_dissolve.test.cjs",
            "tools/equipment_enhancement.test.cjs",
            "tools/economy_write_transaction.test.cjs",
            "tools/event_currency.test.cjs",
            "tools/free_first_deduction.test.cjs",
            "tools/gacha_write_transaction.test.cjs",
            "tools/item_sell_awake_publication.test.cjs",
            "tools/item_use_cultivate_pack.test.cjs",
            "tools/inventory_write_transaction.test.cjs",
            "tools/inventory_rules.test.cjs",
            "tools/party_loadout_validation.test.cjs",
            "tools/quest_write_transaction.test.cjs",
            "tools/single_continue_route.test.cjs",
            "tools/single_continue_route_errors.test.cjs",
            "tools/score_reward_lottery.test.cjs",
            "tools/reward_campaign.test.cjs",
            "tools/shop_purchase_plan.test.cjs",
            "tools/shop_purchase_owner.test.cjs",
            "tools/shop_response_projector.test.cjs",
            "tools/exchange_response_projection.test.cjs",
            "tools/mail_notification.test.cjs",
            "tools/mail_notification_write_routes.test.cjs",
            "tools/mail_reward_fixture.test.cjs",
            "tools/mail_reward_rollback.test.cjs",
            "tools/login_bonus_route.test.cjs",
        ],
    },
    "integration:reward-grant": {
        execution: "serial",
        timeoutMs: 60_000,
        tests: [
            "tools/reward_grant_typed_contract.test.cjs",
            "tools/reward_grant_typed_contract_adversarial.test.cjs",
            "tools/reward_grant_typed_executor.test.cjs",
            "tools/reward_grant_typed_executor_failures.test.cjs",
            "tools/reward_grant_overflow.test.cjs",
            "tools/login_bonus_settlement.test.cjs",
            "tools/reward_grant_architecture.test.cjs",
            "tools/score_reward_selection_core.test.cjs",
            "tools/score_reward_selection.test.cjs",
            "tools/common_response_acquisition.test.cjs",
            "tools/single_settlement_reward_grant.test.cjs",
            "tools/task23c_reward_grants.test.cjs",
            "tools/mail_reward_grant.test.cjs",
            "tools/mail_reward_owner.test.cjs",
            "tools/load_scheduled_resource_settlement.test.cjs",
            "tools/scheduled_resource_rules.test.cjs",
            "tools/scheduled_resource_settlement.test.cjs",
            "tools/gift_receive_transaction.test.cjs",
        ],
    },
    "integration:database": {
        execution: "serial",
        tests: [
            "tools/shop_purchase_count_storage.test.cjs",
            "tools/account_cleanup_admin.test.cjs",
            "tools/account_cleanup_takeover.test.cjs",
            "tools/admin_scheduled_resource_routes.test.cjs",
            "tools/admin_player_actions.test.cjs",
            "tools/admin_mail_expiry.test.cjs",
            "tools/gift_redemption_save_lifecycle.test.cjs",
            "tools/history_receive_route.test.cjs",
            "tools/inventory_owner.test.cjs",
            "tools/inventory_owner_structure.test.cjs",
            "tools/perf/item_inventory_expiry_admission.test.cjs",
            "tools/inventory_cap.test.cjs",
            "tools/item_overflow_direct_settlement.test.cjs",
            "tools/load_event_trade_expiry.test.cjs",
            "tools/mail_overflow.test.cjs",
            "tools/mail_receive_transaction.test.cjs",
            "tools/mission_category_batch_read.test.cjs",
            "tools/player_history_profile_route.test.cjs",
            "tools/player_save_v2.test.cjs",
            "tools/gacha_save_validation.test.cjs",
            "tools/character_growth_save_validation.test.cjs",
            "tools/receive_history_retention.test.cjs",
            "tools/scheduled_resource_storage.test.cjs",
            "tools/server_gameplay_settings.test.cjs",
            "tools/news_storage.test.cjs",
            "tools/schema23_news_migration.test.cjs",
            "tools/schema24_gift_migration.test.cjs",
            "tools/schema25_gacha_state_migration.test.cjs",
            "tools/test-workflow/database-isolation.test.cjs",
            "tools/test-workflow/database-lifecycle.test.cjs",
            "tools/test-workflow/runtime-data-paths.test.cjs",
            "tools/test-workflow/schema20_resource_migration.test.cjs",
            "tools/schema28_follow_migration.test.cjs",
            "tools/follow_domain.test.cjs",
            "tools/account_binding.test.cjs",
            "tools/sp_auth.test.cjs",
            "tools/bind_gate.test.cjs",
            "tools/follow_routes.test.cjs",
            "tools/stamina_serialization.test.cjs",
            "tools/sql_write_shape.test.cjs",
        ],
    },
    "integration:event": {
        execution: "parallel",
        timeoutMs: 60_000,
        tests: [
            "tools/box_gacha_exec_transaction.test.cjs",
            "tools/carnival_rewards.test.cjs",
            "tools/event_settlement_descriptor.test.cjs",
            "tools/event_settlement_hook.test.cjs",
            "tools/event_route_reachability.test.cjs",
            "tools/how_to_get_route.test.cjs",
            "tools/practice_battle_history.test.cjs",
            "tools/practice_battle_history_route.test.cjs",
            "tools/raid_event_master.test.cjs",
            "tools/raid_event_overall_rewards.test.cjs",
            "tools/raid_event_state.test.cjs",
            "tools/raid_event_summary.test.cjs",
            "tools/raid_event_summary_route.test.cjs",
            "tools/ranking_event_route.test.cjs",
            "tools/rush_event_battle_flow.test.cjs",
            "tools/rush_event_shop_route.test.cjs",
            "tools/rush_event_reset_route.test.cjs",
            "tools/rush_final_operation_override.test.cjs",
            "tools/shop_campaign_lineup.test.cjs",
            "tools/shop_sales_list_bulk_reads.test.cjs",
            "tools/score_attack_history.test.cjs",
            "tools/score_attack_history_route.test.cjs",
            "tools/score_attack_route_transaction.test.cjs",
        ],
    },
    "integration:mission": {
        execution: "parallel",
        timeoutMs: 120_000,
        tests: [
            "tools/character_awake_battle_tracker.test.cjs",
            "tools/character_awake_facts.test.cjs",
            "tools/character_awake_lavu_route.test.cjs",
            "tools/character_awake_route.test.cjs",
            "tools/character_awake_settlement.test.cjs",
            "tools/character_awake_unlock.test.cjs",
            "tools/awake_fact_scope.test.cjs",
            "tools/awake_owner_fact_publication.test.cjs",
            "tools/character_growth_owner_publication.test.cjs",
            "tools/character_growth_owner_transactions.test.cjs",
            "tools/awake_request_context.test.cjs",
            "tools/character_growth_writer_boundary.test.cjs",
            "tools/load_awake_full_recovery.test.cjs",
            "tools/mission_awake_evaluation_settlement.test.cjs",
            "tools/mission_awake_reward_owner.test.cjs",
            "tools/mission_awake_session.test.cjs",
            "tools/post_commit_awake_owner.test.cjs",
            "tools/character_election_route.test.cjs",
            "tools/mission_battle_facts.test.cjs",
            "tools/mission_auto_settlement_route.test.cjs",
            "tools/mission_get_progress_transaction.test.cjs",
            "tools/mission_progress_stage_b.test.cjs",
            "tools/mission_progress_stage_b_route.test.cjs",
            "tools/mission_progress_stage_b_integration.test.cjs",
            "tools/mission_degree_response_composition.test.cjs",
            "tools/mission_response_fragment.test.cjs",
            "tools/mission_reward_invalidation.test.cjs",
            "tools/mission_reward_invalidation_integration.test.cjs",
            "tools/mission_collect_progress.test.cjs",
            "tools/mission-client-check-diagnostics.test.cjs",
            "tools/mission_coverage_audit.test.cjs",
            "tools/mission_daily_battle_facts.test.cjs",
            "tools/mission_daily_history_replay.test.cjs",
            "tools/mission_degree_candidates.test.cjs",
            "tools/mission_degree_battle_context.test.cjs",
            "tools/mission_degree_characterization.test.cjs",
            "tools/mission_degree_content_cache.test.cjs",
            "tools/mission_degree_content_tables.test.cjs",
            "tools/mission_degree_context_scope.test.cjs",
            "tools/mission_degree_custom_catalog.test.cjs",
            "tools/mission_degree_immutable.test.cjs",
            "tools/mission_degree_oracle_independence.test.cjs",
            "tools/mission_degree_progress.test.cjs",
            "tools/mission_degree_reference_regressions.test.cjs",
            "tools/mission_degree_session_context.test.cjs",
            "tools/mission_degree_session_selection.test.cjs",
            "tools/mission_degree_settlement_session.test.cjs",
            "tools/mission_degree_settlement_semantics.test.cjs",
            "tools/mission_degree_settlement_failure.test.cjs",
            "tools/mission_degree_second_board_scope.test.cjs",
            "tools/mission_event_battle_facts.test.cjs",
            "tools/mission_event_current_state.test.cjs",
            "tools/mission_event_immutable.test.cjs",
            "tools/mission_event_entry_facts.test.cjs",
            "tools/mission_raid_set_party_route.test.cjs",
            "tools/mission_event_login_route.test.cjs",
            "tools/mission_event_oracle_independence.test.cjs",
            "tools/mission_event_progress.test.cjs",
            "tools/mission_event_session_scope.test.cjs",
            "tools/mission_event_session_semantics.test.cjs",
            "tools/mission_event_session_settlement.test.cjs",
            "tools/mission_collected_items_batch.test.cjs",
            "tools/mission_collect_session_invariant.test.cjs",
            "tools/mission_collect_session_scope.test.cjs",
            "tools/mission_collect_session_settlement.test.cjs",
            "tools/mission_evaluation_production_loaders.test.cjs",
            "tools/mission_shop_purchases_fact_loader.test.cjs",
            "tools/mission_evaluation_quest_scoped.test.cjs",
            "tools/mission_evaluation_session.test.cjs",
            "tools/mission_fact_key.test.cjs",
            "tools/mission_fact_requirements.test.cjs",
            "tools/mission_master_value.test.cjs",
            "tools/mission_raid_summary_route.test.cjs",
            "tools/mission_active_content.test.cjs",
            "tools/mission_active_core.test.cjs",
            "tools/active_mission_plan.test.cjs",
            "tools/active_mission_owner_publication.test.cjs",
            "tools/active_mission_operation_publication.test.cjs",
            "tools/active_mission_counter_storage.test.cjs",
            "tools/active_mission_fact_session.test.cjs",
            "tools/active_mission_ex_quest_clear_facts.test.cjs",
            "tools/active_mission_fixed_point.test.cjs",
            "tools/party_action_counter.test.cjs",
            "tools/expod_inject_exp_route.test.cjs",
            "tools/active_mission_reconciliation.test.cjs",
            "tools/active_mission_character_facts.test.cjs",
            "tools/active_mission_battle_facts.test.cjs",
            "tools/active_mission_chapter_facts.test.cjs",
            "tools/active_mission_quest_challenge.test.cjs",
            "tools/active_mission_specific_party_facts.test.cjs",
            "tools/active_mission_batch_facts.test.cjs",
            "tools/active_mission_conditional_battle_facts.test.cjs",
            "tools/active_mission_specific_battle_facts.test.cjs",
            "tools/active_mission_receive_route.test.cjs",
            "tools/contents_guide_start_route.test.cjs",
            "tools/mission_catalog.test.cjs",
            "tools/mission_pass.test.cjs",
            "tools/mission_pass_battle_facts.test.cjs",
            "tools/mission_pass_content.test.cjs",
            "tools/mission_pass_route.test.cjs",
            "tools/mission_pass_settlement.test.cjs",
            "tools/pass_card_point_change.test.cjs",
            "tools/mission_progress_route.test.cjs",
            "tools/mission_regular_chapter_regressions.test.cjs",
            "tools/mission_regular_facts.test.cjs",
            "tools/mission_regular_session_scope.test.cjs",
            "tools/mission_regular_session_settlement.test.cjs",
            "tools/mission_regular_state_derivation.test.cjs",
            "tools/mission_response_merge.test.cjs",
            "tools/perf/awake_request_context_admission.test.cjs",
            "tools/perf/awake_request_context_baseline.test.cjs",
            "tools/perf/awake_request_context_runner.test.cjs",
            "tools/perf/awake_owner_focused_baseline.test.cjs",
            "tools/perf/mission_engine_focused_admission.test.cjs",
            "tools/perf/mission_engine_focused_baseline.test.cjs",
            "tools/perf/mission_engine_focused_runner.test.cjs",
            "tools/perf/active_mission_metrics.test.cjs",
            "tools/perf/active_mission_workload_overlay.test.cjs",
            "tools/perf/active-mission/baseline.test.cjs",
            "tools/perf/mission_entry_base_oracle.test.cjs",
            "tools/perf/mission_entry_layered_load.test.cjs",
            "tools/perf/mission_entry_load_metrics.test.cjs",
            "tools/perf/non_multi_mixed_active_quests.test.cjs",
            "tools/perf/non_multi_mixed_fixture.test.cjs",
            "tools/perf/non_multi_mixed_http.test.cjs",
            "tools/perf/non_multi_mixed_metrics.test.cjs",
            "tools/perf/non_multi_mixed_scenario_validation.test.cjs",
            "tools/perf/non_multi_mixed_scenarios.test.cjs",
            "tools/perf/non_multi_mixed_workload.test.cjs",
            "tools/perf/sqlite_fault_injection.test.cjs",
            "tools/perf/mission_settlement_baseline.test.cjs",
            "tools/oracle/git-object-runtime.test.cjs",
            "tools/mission_settlement_base_oracle.test.cjs",
            "tools/mission_settlement_evaluate.test.cjs",
            "tools/mission_settlement_pipeline_characterization.test.cjs",
            "tools/mission_settlement_pipeline_interfaces.test.cjs",
            "tools/mission_settlement_pipeline_rollback.test.cjs",
            "tools/mission_settlement_prepare.test.cjs",
            "tools/mission_settlement_scope.test.cjs",
            "tools/mission_settlement.test.cjs",
            "tools/mission_settlement_write.test.cjs",
            "tools/mission_storage.test.cjs",
            "tools/mission_time_utils.test.cjs",
            "tools/pass_card_purchase_route.test.cjs",
            "tools/pass_card_route.test.cjs",
            "tools/stamina_campaign_targeting.test.cjs",
        ],
    },
    "integration:quest": {
        execution: "parallel",
        timeoutMs: 120_000,
        tests: [
            "tools/auto_start_stamina_stop.test.cjs",
            "tools/battle_quest_progress_plan.test.cjs",
            "tools/battle_settlement_boundary.test.cjs",
            "tools/battle_settlement_values.test.cjs",
            "tools/battle_entry_inventory_route.test.cjs",
            "tools/open_period_boundaries.test.cjs",
            "tools/quest_prerequisite_boundaries.test.cjs",
            "tools/raid_battle_stamina.test.cjs",
            "tools/rush_battle_stamina.test.cjs",
            "tools/party_heal_option_persistence.test.cjs",
            "tools/perf/single_battle_settlement_admission.test.cjs",
            "tools/perf/single_battle_settlement_baseline.test.cjs",
            "tools/quest_entry_lifecycle.test.cjs",
            "tools/quest_resource_lifecycle.test.cjs",
            "tools/single_battle_abort_numeric_validation.test.cjs",
            "tools/single_battle_abort_validation.test.cjs",
            "tools/single_battle_identity_reads.test.cjs",
            "tools/quest_host_finish.test.cjs",
            "tools/single_battle_finish_validation.test.cjs",
            "tools/single_finish_authority_transaction.test.cjs",
            "tools/single_finish_final_projection.test.cjs",
            "tools/single_finish_awake_reward_owner.test.cjs",
            "tools/single_finish_response_projector.test.cjs",
            "tools/single_finish_request_validation.test.cjs",
            "tools/story_quest_finish.test.cjs",
            "tools/tutorial_update_step.test.cjs",
        ],
    },
    "integration:party": {
        execution: "parallel",
        // Multi-finish settlement suites are heavyweight (real production
        // homes); 30s parallel default flakes under group load.
        timeoutMs: 120_000,
        tests: [
            "tools/multi_battle_lifecycle.test.cjs",
            "tools/multi_settlement_overflow.test.cjs",
            "tools/perf/multi_settlement_baseline.test.cjs",
            "tools/perf/multi_snapshot_baseline.test.cjs",
            "tools/multi_response_projection.test.cjs",
            "tools/multi_settlement_active_mission.test.cjs",
            "tools/rescue_fragment_reward.test.cjs",
            "tools/special_quest_party.test.cjs",
        ],
    },
    "integration:cdn": {
        execution: "serial",
        timeoutMs: 180_000,
        tests: [
            "tools/asset_mode.test.cjs",
            "tools/asset_mode_compiled_smoke.test.cjs",
            "tools/cdn_asset_import.test.cjs",
            "tools/cn_asset_route.test.cjs",
            "tools/cdn_catalog_provider.test.cjs",
            "tools/cdn_runtime_manifest.test.cjs",
            "tools/cdn_audit.test.cjs",
            "tools/cdn_files.test.cjs",
            "tools/ios_asset_route.test.cjs",
            "tools/combined_startup.test.cjs",
            "tools/ios_leiting_route.test.cjs",
            "tools/version_dis_android.test.cjs",
            "tools/legacy_asset_state.test.cjs",
        ],
    },
    admin: {
        execution: "parallel",
        tests: [
            "tests/admin-account-save-ui.test.js",
            "tests/admin-bindings-ui-source.test.js",
            "tests/admin-cdn-status-source.test.js",
            "tests/admin-clairvoyance.test.js",
            "tests/admin-gameplay-settings-ui-source.test.js",
            "tests/admin-gift-ui-source.test.js",
            "tests/admin-mail-rules.test.js",
            "tests/admin-mail-ui-source.test.js",
            "tests/admin-news-ui-source.test.js",
            "tests/admin-scheduled-resource-ui-source.test.js",
            "tests/admin-time-clairvoyance-ui-source.test.js",
            "tools/admin_gift_routes.test.cjs",
            "tools/admin_news_routes.test.cjs",
            "tools/admin_mail_type_policy.test.cjs",
            "tools/bindings_api.test.cjs",
            "tools/bot_api.test.cjs",
        ],
    },
    generator: {
        execution: "serial",
        tests: [
            "tools/boss_battle_multiscene_content.test.cjs",
            "tools/box_gacha_reset.test.cjs",
            "tools/gacha_odds_export.test.cjs",
            "tools/hard_multi_event_quest.test.cjs",
            "tools/periodic_reward.test.cjs",
            "tools/rebuild_gacha_from_odds.test.cjs",
            "tools/score_attack_event_data.test.cjs",
            "tools/star_grain_material_pack.test.cjs",
            "tools/treasure_key_entry_data.test.cjs",
        ],
    },
    "generator:mission-event": {
        execution: "serial",
        tests: [
            "tools/mission_event_battle_rules.test.cjs",
        ],
    },
})

const quickGroups = Object.keys(TEST_GROUPS).filter(name => name.startsWith("quick:"))
const integrationGroups = Object.keys(TEST_GROUPS).filter(name => name.startsWith("integration:"))

const AGGREGATE_GROUPS = Object.freeze({
    quick: Object.freeze(quickGroups),
    integration: Object.freeze(integrationGroups),
    admin: Object.freeze(["admin"]),
    generator: Object.freeze(["generator", "generator:mission-event"]),
    full: Object.freeze([
        ...quickGroups,
        ...integrationGroups,
        "admin",
        "generator:mission-event",
    ]),
})

module.exports = {
    AGGREGATE_GROUPS,
    TEST_GROUPS,
}
